### ISSUE TITLE
How are variables passed?

### ISSUE THREAD

**Issue by supertylerc** [batfish/ansible-demo#4]
I tried to understand how variables for questions might be passed in this demo.  The questions (`checks/**/*.json`) have a number of optional variables in them, implying that you could, at playbook run time, specify one or more nodes/remote nodes/filters to test against.  But I can't find where the Ansible modules would get those parameters.

**Comment by ratulm** [comment]
Cc: @corinaminer, @sfraint in case you missed this

**Comment by corinaminer** [comment]
Those question parameters aren't currently exposed in the playbooks, and we didn't modify them in our demo scenario. If you just want to try out those questions with some different parameters, the easiest way would be to simply edit the question JSON files themselves -- you can add or modify the `value` field in any variable. For example, here is the variables section of `filter_reachability.json` edited to check only `ACL_1` and `ACL_2` on device `R1`:
```
    "variables": {
      "filters": {
        "description": "Name or regex identifying the filters to test.",
        "type": "string",
        "optional": true,
        "value": "R1"
      },
      "nodes": {
        "description": "Examine filters on nodes matching this name or regex.",
        "type": "nodeSpec",
        "optional": true,
        "value": "ACL_1|ACL_2"
      }
    }
```

You may find the [question documentation](https://pybatfish.readthedocs.io/en/latest/questions.html) useful for modifying parameters (and feel free to ask questions on [our Slack channel](https://batfish-org.slack.com/)). After modifying a question, make sure to do `python python/demo-setup.py -a "DC Fabric Policy" checks/fabric/ -a "DC Base Policy" checks/base/` to update the questions in Batfish before running the playbooks again.

It's also totally feasible to write an Ansible playbook to modify question parameters, but we don't have such a playbook in the demo -- if you're interested in attempting that, we're happy to support you. We are also planning to build some playbooks in the next few weeks that will make it easy to generate checks with custom parameters.

**Comment by supertylerc** [comment]
Thanks for the info @corinaminer.  I think for now I'll stick to using templates to generate the checks files with whatever variables I want to use.

This can be closed or left open if you want to use it to track adding the feature.
